Update dependency versions and build script
democracyworks/kraken-works-lein-template pull request #21
Opened 2018-06-18 20:01 UTC by mrichards42

Based on changes I had to make for `crm-works`

2018-06-27 13:01 UTC, cap10morgan requested changes
Thanks for doing this! It's very helpful but easy to neglect.

Just one thing to look into w/r/t dep versions.

2018-06-27 13:01 UTC, cap10morgan commented on resources/leiningen/new/kraken_works/project.clj
> +                 [democracyworks/kehaar "0.11.3"]]
Version 0.11.4 of kehaar was released on Jan. 26. Can we make sure all these deps are the latest (compatible) releases?

2018-06-27 14:31 UTC, mrichards42 commented
Everything's up to date now according to `lein ancient`. Looks like the datomic changes are [minor](https://docs.datomic.com/on-prem/changes.html) as well.

2018-09-05 18:23 UTC, mrichards42 commented
Some of the deps are out of date, and some of the changes are no longer necessary, so I'll close and open a new PR

2018-09-05 18:23 UTC, closed without merging